-- 000004_create_messages_table.up.sql
CREATE TABLE messages (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           BIGINT       NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,

    sender_type         VARCHAR(20)  NOT NULL,
    sender_name         VARCHAR(150) NULL,
    message             TEXT         NOT NULL DEFAULT '',

    attachment_type     VARCHAR(20)  NULL,
    attachment_path     TEXT         NULL,
    attachment_mime     VARCHAR(100) NULL,
    attachment_size     BIGINT       NULL,

    -- Sinkronisasi Telegram & idempotensi
    telegram_message_id BIGINT       NULL,
    delivery_status     VARCHAR(10)  NOT NULL DEFAULT 'sent',   -- pending | sent | failed
    client_msg_id       UUID         NULL,                      -- dari widget, untuk retry aman

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT chk_messages_sender_type
        CHECK (sender_type IN ('user', 'ai', 'programmer', 'system')),
    CONSTRAINT chk_messages_attachment_type
        CHECK (attachment_type IS NULL OR attachment_type IN ('image', 'video', 'document')),
    CONSTRAINT chk_messages_attachment_pair
        CHECK ((attachment_type IS NULL) = (attachment_path IS NULL)),
    CONSTRAINT chk_messages_not_empty
        CHECK (message <> '' OR attachment_path IS NOT NULL),
    CONSTRAINT chk_messages_delivery_status
        CHECK (delivery_status IN ('pending', 'sent', 'failed'))
);

-- Query riwayat chat per tiket
CREATE INDEX idx_messages_ticket_id_id ON messages (ticket_id, id);

-- Retry dari widget tidak membuat pesan ganda
CREATE UNIQUE INDEX uq_messages_client_msg
    ON messages (ticket_id, client_msg_id) WHERE client_msg_id IS NOT NULL;

-- Antrian outbox: pesan yang belum/gagal terkirim ke Telegram
CREATE INDEX idx_messages_outbox
    ON messages (id) WHERE delivery_status IN ('pending', 'failed');
