-- 000002_create_tenants_table.up.sql
CREATE TABLE tenants (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_identifier  VARCHAR(100) NOT NULL UNIQUE,            -- contoh: kemkes_1101015
    app_name        VARCHAR(100) NOT NULL,                   -- contoh: KlikMedic SIMRS
    tenant_name     VARCHAR(150) NOT NULL,                   -- contoh: RSUD Meuraxa
    api_key_hash    CHAR(64)     NOT NULL UNIQUE,            -- sha256 hex dari API key (key asli tidak disimpan)
    allowed_origins TEXT[]       NOT NULL DEFAULT '{}',      -- whitelist CORS / WS origin
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_tenants_updated_at
    BEFORE UPDATE ON tenants
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
