-- 000003_create_tickets_table.up.sql
CREATE TABLE tickets (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             UUID         NOT NULL DEFAULT gen_random_uuid() UNIQUE,  
    tenant_id             BIGINT       NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    ticket_code           VARCHAR(50)  NOT NULL UNIQUE,                           

    user_id               VARCHAR(100) NOT NULL,
    user_name             VARCHAR(150) NOT NULL,
    module_name           VARCHAR(100) NOT NULL DEFAULT 'Umum',
    diagnostic_info       JSONB        NULL,

    status                VARCHAR(20)  NOT NULL DEFAULT 'open',

    -- Telegram
    telegram_thread_id    BIGINT       NULL,     -- Forum Topic (ada setelah diklaim)
    tg_card_message_id    BIGINT       NULL,     -- message_id kartu di General (untuk editMessageText)
    assigned_programmer   VARCHAR(150) NULL,     -- nama tampilan
    assigned_tg_user_id   BIGINT       NULL,     -- id Telegram pengklaim

    -- CSAT
    csat_rating           SMALLINT     NULL,
    csat_review           TEXT         NULL,
    -- Timeline
    claimed_at            TIMESTAMPTZ  NULL,
    resolved_at           TIMESTAMPTZ  NULL,
    last_user_message_at  TIMESTAMPTZ  NULL,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_tickets_status
        CHECK (status IN ('open', 'escalated', 'resolved')),
    CONSTRAINT chk_tickets_escalated_has_programmer
        CHECK (status <> 'escalated' OR (assigned_programmer IS NOT NULL AND claimed_at IS NOT NULL)),
    CONSTRAINT chk_tickets_resolved_has_time
        CHECK (status <> 'resolved' OR resolved_at IS NOT NULL),
    CONSTRAINT chk_tickets_csat_rating
        CHECK (csat_rating IS NULL OR csat_rating BETWEEN 1 AND 5)
);

-- Satu thread Telegram = satu tiket
CREATE UNIQUE INDEX uq_tickets_thread_id
    ON tickets (telegram_thread_id) WHERE telegram_thread_id IS NOT NULL;

-- Maksimal 1 tiket aktif per user per tenant (aman dari race dua request bersamaan)
CREATE UNIQUE INDEX uq_tickets_active_per_user
    ON tickets (tenant_id, user_id) WHERE status <> 'resolved';

CREATE INDEX idx_tickets_tenant_status ON tickets (tenant_id, status);

-- Untuk job auto-close tiket yang lama tidak aktif
CREATE INDEX idx_tickets_autoclose
    ON tickets (last_user_message_at) WHERE status <> 'resolved';

CREATE TRIGGER trg_tickets_updated_at
    BEFORE UPDATE ON tickets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
